config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
    resources :comments
  end

  resources :admins     
   root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, length: { minimum: 5 }
	has_many :comments, dependent: :destroy
	belongs_to :user
	paginates_per 2
	has_many :attachments, :as => :attachable, dependent: :destroy
    accepts_nested_attributes_for :attachments
	# # validate do |school|
 # #    article.comments.each do |comment|
 # #      next if comment.valid?
 # #      comment.errors.full_messages.each do |msg|
 # #        # you can customize the error message here:
 # #        errors[:base] << "Student Error: #{msg}"
 # #      end
 # #    end
 #  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
	belongs_to :attachable, polymorphic: true
	
	has_attached_file :avatar
	validate :check_type, on: :create
	do_not_validate_attachment_file_type :avatar
 	def check_type
 		if attachable_type == "User"
			unless avatar_content_type.match(/\Aimage\/.*\z/)  
				errors.add(:avatar_content_type, "must be an image")
			end
		elsif attachable_type == "Article"
			 unless ["application/pdf"].include? avatar_content_type  
				errors.add(:avatar_content_type, "must be an image or pdf")
			end
		end
			
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
	validates :commenter, :body, length: { in: 6..20 }
	paginates_per 2
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  has_and_belongs_to_many :roles
  has_many :articles
  accepts_nested_attributes_for :roles
  validates :email, uniqueness: true
  validate :validate_username
  validates :username, presence: :true, uniqueness: { case_sensitive: false } 
  has_one :attachment, as: :attachable
  accepts_nested_attributes_for :attachment 


  
	def validate_username
  		if User.where(email: username).exists?
    		errors.add(:username, :invalid)
  		end
	end

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def roles_attributes=(attributes)
  	keys = []
  	attributes.keys.each do |k|
  		keys << attributes[k]["id"]
  	end
  	if keys.length > 0
  		self.roles = Role.where(id: keys)
  	end
  end

 def self.find_first_by_auth_conditions(warden_conditions)
  	conditions = warden_conditions.dup
  	conditions = warden_conditions.dup
  	conditions[:email].downcase! if conditions[:email]
  	if login = conditions.delete(:login)
    	where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  	else
    	if conditions[:username].nil?
      		where(conditions).first
    	else
      		where(username: conditions[:username]).first
    	end
  	end
  end



end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end
 
  def show
  	@user = User.find(params[:id])
  end
 
  def new
    @user = User.new
  end
 
  def edit
  	@user = User.find(params[:id])
  end
 
  def create
    @user = User.new(user_params)
 
    if @user.save
      redirect_to admin_path(@user), notice: "User succesfully created!"
    else
      render 'new'
    end
  end
 
  def update
    @user = User.find(params[:id])
    if @user.update_without_password(user_params)
      redirect_to admin_url(@user)
    else
      render 'edit'
    end
  end
 
  def destroy
  	@user = User.find(params[:id])
    @user.destroy
    redirect_to admins_path
  end
 

  private
  def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, attachment_attributes: [:id, :avatar])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
  	if resource.roles.pluck(:name).include? "admin"
  		admins_path
  	else
  		puts "not found"
  		root_path
  	end
  end

protected
  def configure_permitted_parameters
	added_attrs = [:username, :remember_me, :email, :password, :password_confirmation, attachment_attributes: [:id, :avatar], roles_attributes: [:id, :name]]
    
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_attributes, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.order(:title).page params[:page]
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @articles}
      format.json { render json: @articles}
    end
  end
 
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments.page(params[:page])
  end
 
  def new
    @article = current_user.articles.build
    @article.attachments.build
  end
 
  def edit
  end
 
  def create
    @article = current_user.articles.build(article_params)
 
    if @article.save
    	flash[:notice] = "Successfully created product."
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text, attachments_attributes: [:id, :avatar, :_destroy])
    end

    def find_attributes
    	@article = Article.find(params[:id])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @article.comments.build(comment_params)
    @article.save
    render 'articles/show'
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/edit.html.erb
<%= form_for(@user, url: admin_path(@user), html: { multipart: true }) do |f| %>




<% unless @user.attachment.nil? %>
<%= image_tag @user.attachment.avatar.url %>
<%end%>
  <div class="field">
<%= f.file_field :avatar %>
</div>

  <div class="field">
    <p><%= f.label :username %><br />
    <%= f.text_field :username %></p>
  </div>


  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>


  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/admins/index.html.erb
<h1>Listing users</h1>
 <%= link_to 'New User', new_admin_path %>
<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
 
  <% @users.each do |user| %>
  <% unless user == current_user %>
    <tr>
      <td><%= user.username %></td>
      <td><%= link_to 'Show', admin_path(user) %></td>
      <td><%= link_to 'Edit', edit_admin_path(user) %></td>
      <td><%= link_to 'Destroy', admin_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>

    <%end%>

  <% end %>
</table>

app/views/admins/new.html.erb
<h2>Create user</h2>
<%= form_for(@user, url: admins_path(@user), html: { multipart: true }) do |f| %>
<% @user.build_attachment %>
<div class="field">
<%= f.fields_for :attachment do |r| %>
  <%= r.file_field :avatar %>
<% end %>
</div>

  <div class="field">
    <p><%= f.label :username %><br />
    <%= f.text_field :username %></p>
  </div>


  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/admins/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.username %>
</p>
 
<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Back', admins_path %>

app/views/articles/_attachment_fields.html.erb
<div class='nested-fields'>
    <div class="field">
    <%= f.file_field :avatar %>
    </div>
    <%= link_to_remove_association "remove task", f %>
</div>

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :multipart => true } do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div>
    Upload Image
    <%= f.fields_for :attachments  do |attachment| %>
      <%= render 'attachment_fields', :f => attachment %>
    <% end %> 

    <div class='links'>
      <%= link_to_add_association 'add attachment', f, :attachments %>
    </div>


  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
 <%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>User</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.user.email %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <% if article.user == current_user %>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <%end%>
    </tr>
  <% end %>
</table>


<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @comments %>
 
 <%= paginate @comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

             <% if user_signed_in? %>
             <%= link_to "Sign_out", destroy_user_session_path, :method => :delete %>
             <%= link_to "Profile", edit_user_registration_path %>

             <%else%>
             <%= link_to "Sign_up", new_user_registration_path %>
             <%= link_to "Sign_in", new_user_session_path %>
             <%end%>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>hello, Rails</h1>
<%= link_to 'My Blog', controller:'articles' %>